In [2]:
import pandas as pd

In [3]:
df = pd.read_excel("All India Village data.xlsx")

In [6]:
print("shape",df.shape)

shape (577647, 8)

In [7]:
df.head()

,MDDS STC,STATE NAME,MDDS DTC,DISTRICT NAME,MDDS Sub_DT,SUB-DISTRICT NAME,MDDS PLCN,Area Name
0,9,UTTAR PRADESH,175,Allahabad,893,Handia,162519,Sarai Hariram
1,9,UTTAR PRADESH,175,Allahabad,893,Handia,162520,Pindauna
2,9,UTTAR PRADESH,175,Allahabad,893,Handia,162521,Ugrsenpur Urf Bibipur
3,9,UTTAR PRADESH,175,Allahabad,893,Handia,162522,Kandharpur
4,9,UTTAR PRADESH,175,Allahabad,893,Handia,162523,Purethakurain

In [6]:
df.columns

Index(['MDDS STC', 'STATE NAME', 'MDDS DTC', 'DISTRICT NAME', 'MDDS Sub_DT',
       'SUB-DISTRICT NAME', 'MDDS PLCN', 'Area Name'],
      dtype='object')

In [9]:
df.columns = ["state_code" , "state_name","district_code","district_name","subdistrict_code","subdistrict_name","village_code","village_name"]

In [10]:
df.columns

Index(['state_code', 'state_name', 'district_code', 'district_name',
       'subdistrict_code', 'subdistrict_name', 'village_code', 'village_name'],
      dtype='object')

In [11]:
df.head()

,state_code,state_name,district_code,district_name,subdistrict_code,subdistrict_name,village_code,village_name
0,9,UTTAR PRADESH,175,Allahabad,893,Handia,162519,Sarai Hariram
1,9,UTTAR PRADESH,175,Allahabad,893,Handia,162520,Pindauna
2,9,UTTAR PRADESH,175,Allahabad,893,Handia,162521,Ugrsenpur Urf Bibipur
3,9,UTTAR PRADESH,175,Allahabad,893,Handia,162522,Kandharpur
4,9,UTTAR PRADESH,175,Allahabad,893,Handia,162523,Purethakurain

In [17]:
before = df.shape[0]
df = df.drop_duplicates()

In [18]:
after = df.shape[0]
print("duplicates removed" , before - after)

duplicates removed 0

In [19]:
df.isnull().sum()

state_code          0
state_name          0
district_code       0
district_name       0
subdistrict_code    0
subdistrict_name    0
village_code        0
village_name        0
dtype: int64

In [20]:
(df==0).sum()

state_code          0
state_name          0
district_code       0
district_name       0
subdistrict_code    0
subdistrict_name    0
village_code        0
village_name        0
dtype: int64

In [22]:
df.to_csv("cleaned_village_data.csv",index=False)
df.to_excel("cleaned_village_data.xlsx",index=False)

In [3]:
state_df = pd.read_csv("states.csv")
district_df = pd.read_csv("districts.csv")
sub_district_df = pd.read_csv("sub_districts.csv")
village_df = pd.read_csv("Villages.csv")

In [4]:
state_df.columns = ["state_code" , "state_name"]

In [5]:
state_df.head()

   state_code      state_name
0           9   UTTAR PRADESH
1          23  MADHYA PRADESH
2          21          ODISHA
3          10           BIHAR
4           8       RAJASTHAN

In [6]:
district_df.columns = ["state_code" , "district_code","district_name"]

In [8]:
district_df.head()

   state_code  district_code district_name
0           9            175     Allahabad
1           9            134        Bijnor
2           9            179     Sultanpur
3           9            154       Sitapur
4           9            152  Shahjahanpur

In [8]:
sub_district_df.columns = ["district_code" , "sub_district_code","sub_district_name"]
sub_district_df.head()

   district_code  sub_district_code sub_district_name
0            175              893.0            Handia
1            175              889.0           Phulpur
2            175              888.0            Soraon
3            175              894.0              Meja
4            175              892.0         Karchhana

In [6]:
village_df.columns = ["sub_district_code" , "village_code","village_name"]
village_df.head()

   sub_district_code  village_code           village_name
0              893.0        162519          Sarai Hariram
1              893.0        162520               Pindauna
2              893.0        162521  Ugrsenpur Urf Bibipur
3              893.0        162522             Kandharpur
4              893.0        162523          Purethakurain

In [5]:
state_df.to_csv("states.csv",index=False)

In [7]:
district_df.to_csv("districts.csv",index=False)

In [9]:
sub_district_df.to_csv("sub_districts.csv",index=False)

In [15]:
village_df.to_csv("villages.csv",index=False)